apiVersion: v1
kind: Service
metadata:
  name: ohad-service
spec:
  selector:
    app: ohad-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
    nodePort: 31515
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohad-app 
spec:
  selector:
    matchLabels:
      app: ohad-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ohad-app
    spec:
      containers:
      - name: ohad-app
        image: ohadz/ohad-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
